FORMAT: 1A

# Meli Data Centers API
The datacenter REST API will be used to expose details for a data center management application.

# Group Observation
Observation related resources of the **Data Centers API**

## Observation [/observation/{id}]
A single observation object.

The observation resource has the following attributes:

- id
- status
- recordType
- type
- conditions
- name
- title
- description
- referenceUrl
- assetId
- spaceId
- reasonForIgnore
- value
- valueType
- rejectionReason
- rejectionComment

+ Parameters
    + id (string) ... ID of the observation to perform various operations.

+ Model (application/json)
    JSON representation of Observation resource.
    
    + Body
            {
                "id": "a02F0000009GoV5"
                "status": "New"
                "recordType": "Alert"
                "type": "Power"
                "conditions": "Power"
                "name": "My Observation"
                "title": "My New Observation: More Detail"
                "description": "rich text"
                "referenceUrl": "url"
                "assetId": "a03F000000A2lm3"
                "spaceId": "a05F000000AS2KJ"
                "reasonForIgnore": "Not Relevant"
                "value": "dollar"
                "valueType": "Efficiency"
                "rejectionReason": "Too Big / Too Complex"
                "rejectionComment": "Revisit and provide brief data"
            }

### Get a Single Observation [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
